name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Automated test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JSON to DotEnv
        uses: the-pistol/github-action-json-to-dotenv@master
        with:
          input-json: '.github/workflows/test-1.json'
          output-dotenv: '.github/workflows/.env'

      - name: dump generated DotEnv file
        shell: bash
        run: |
          cat .github/workflows/.env      

      - name: Load dotenv file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows

      - name: Use vars
        shell: bash
        run: |
          echo "${{ env.var1 }}"    
          
